<?php

	$palestras = array();

	/*
	$palestras['exemplo']['titulo']      = "";
	$palestras['exemplo']['descricao']   = "";
	$palestras['exemplo']['palestrante'] = "";
	$palestras['exemplo']['biografia']   = "";
	*/

	$palestras['scrum-ou-kanban-qual-voce-usaria']['titulo']      = "Scrum ou Kanban, qual você usaria?";
	$palestras['scrum-ou-kanban-qual-voce-usaria']['descricao']   = "A palestra será uma comparação entre os métodos ágeis Scrum e Kanban e quais são os cenários que levam um time adotar um outro framework de desenvolvimento.  Além dos conceitos sobre os métodos, exemplos práticos e vivenciados no dia-a-dia de empresas e times onde tive a oportunidade de aplicar esses frameworks.";
	$palestras['scrum-ou-kanban-qual-voce-usaria']['palestrante'] = "César Augusto Felix Leite - UOL";
	$palestras['scrum-ou-kanban-qual-voce-usaria']['biografia']   = "Mozair é um desenvolvedor multidisciplinar entusiasta de XP, Kanban e Lean.Formado em Ciência da Computação pela UFSCar (2004~2007), chegou a atuar como gerente de projetos pela Accenture, hoje atua como desenvolvedor/consultor pela ThoughtWorks. Durante esta jornada, participou da implantação e aplicação de métodos tradicionais e ágeis em projetos envolvendo clientes e parceiros em diversas localidades, como EUA, India, Italia e Brasil. Evangelista de boas práticas, já passou por vários cantos do Brasil falando sobre cultura ágil, refactoring, javascript e ruby. Recentemente esteve presente na Agile India (2012) e Ruby Conf Uruguay (2011).";
	
	
	$palestras['me-formei-e-agora']['titulo']      = "Me formei, e agora?";
	$palestras['me-formei-e-agora']['descricao']   = "nesta apresentação falaremos um pouco sobre o estado do mercado e os tipos de papéis que podem ser desempenhados no mundo de desenvolvimento de software";
	$palestras['me-formei-e-agora']['palestrante'] = "Mozair - ThoughtWorks";
	$palestras['me-formei-e-agora']['biografia']   = "Mozair é um desenvolvedor multidisciplinar entusiasta de XP, Kanban e Lean.Formado em Ciência da Computação pela UFSCar (2004~2007), chegou a atuar como gerente de projetos pela Accenture, hoje atua como desenvolvedor/consultor pela ThoughtWorks. Durante esta jornada, participou da implantação e aplicação de métodos tradicionais e ágeis em projetos envolvendo clientes e parceiros em diversas localidades, como EUA, India, Italia e Brasil. Evangelista de boas práticas, já passou por vários cantos do Brasil falando sobre cultura ágil, refactoring, javascript e ruby. Recentemente esteve presente na Agile India (2012) e Ruby Conf Uruguay (2011).";
	
	$palestras['crowd-pairing']['titulo']      = "Mini curso sobre testing and refactoring";
	$palestras['crowd-pairing']['descricao']   = " nesta sessão, convidamos você a participar do desenvolvimento de uma pequena funcionalidade, vamos trabalhar juntos com foco em testes e refactoring";
	$palestras['crowd-pairing']['palestrante'] = "Mozair - ThoughtWorks";
	$palestras['crowd-pairing']['biografia']   = "";
	
		
	$palestras['introducao-ao-rails']['titulo']      = "Mini curso de Ruby on Rails";
	$palestras['introducao-ao-rails']['descricao']   = "Criado em 2005 pelo dinamarquês David Heinemeier Hansson, o framework de código aberto Ruby on Rails é hoje uma das principais alternativas para o desenvolvimento de aplicações web. Focado na simplicidade e no minimalismo, o framework foca bastante em manter o código conciso e na eficiência do programador em desenvolver novas funcionalidades. Esse curso dará uma visão geral da linguagem Ruby e do framework Ruby on Rails, desenvolvendo uma aplicação simples, totalmente orientada a testes e daremos também algumas dicas de boas práticas no desenvolvimento de aplicações web que aprendemos no nosso dia-a-dia.";
	$palestras['introducao-ao-rails']['palestrante'] = "Rodrigo Flores";
	$palestras['introducao-ao-rails']['biografia']   = "Nascido em São Paulo, Rodrigo Flores tem 25 anos, é formado em ciência da computação pelo IME-USP e trabalha para a Plataformatec desde 2010. Trabalha com o desenvolvimento de aplicações web usando Ruby on Rails desde 2009 e já contribuiu para diversos projetos open source como o próprio Rails, o middleware Rack, entre outros. Hoje, Rodrigo Flores, é um dos mantenedores do Devise uma das bibliotecas de autenticação mais utilizadas em aplicações Ruby on Rails.";
	
	
	$palestras['why-know-agile']['titulo']      = "Why Know Agile";
	$palestras['why-know-agile']['descricao']   = "O que significa ser ágil? Muito se ouve sobre o uso de metodologias ágeis para o desenvolvimento de software, mas o que isso significa? Quais os princípios que norteiam o desenvolvimento ágil? Como diferem das chamadas \"metodologias tradicionais\"? Como isso aumenta nossas chances de sucesso no desenvolvimento de software? Ao longo da palestra, apresentaremos a visão da Plataformatec em relação a estes pontos e porque apostamos que este tipo de abordagem faz sentido para o desenvolvimento de aplicativos voltados à internet.";
	$palestras['why-know-agile']['palestrante'] = "Rafael Ozaki - Plataformatec";
	$palestras['why-know-agile']['biografia']   = "Rafael Ozaki é Engenheiro Naval, formado pela Escola Politécnica da USP. Após trabalhar por 3 anos com consultoria estratégica, juntou-se em 2010 à Plataformatec, onde tem atuado no desenvolvimento de novos negócios e junto aos times de desenvolvimento em projetos voltados à internet.";
	
	$palestras['os-desafios-de-ti-no-e-commerce']['titulo']      = "Os desafios de TI no e-commerce";
	$palestras['os-desafios-de-ti-no-e-commerce']['descricao']   = "Nosso objetivo é apresentar para este público de TI como está o mercado de e-commerce e os desafios encontrados neste negócio";
	$palestras['os-desafios-de-ti-no-e-commerce']['palestrante'] = "Rafael Barini e Gustavo Augusto Silva Avelar - Nova Pontocom";
	$palestras['os-desafios-de-ti-no-e-commerce']['biografia']   = " Rafael Barini : Gerente de projetos Bacharel em Ciencia da Computação, Unifran MBA em Tecnologia e Negócios na Internet – Ufscar/FAI; Gustavo Augusto Silva Avelar:Engenharia de Produção – UFMG; Diretor Adjunto de Marketing ";
	
	$palestras['a-semente-nao-entendida-de-todas-as-metodologias']['titulo']      = "A Semente não entendida de todas as metodologias";
	$palestras['a-semente-nao-entendida-de-todas-as-metodologias']['descricao']   = "É muito fácil ficar confuso com tantas novas metodologias ou processos que existem no mercado de TI. Desde tradicionais que envolvem coisas como ISO ou CMMi até as ditas ’modernas’ e ’ágeis’ como Scrum, Extreme Programming, Crystal, e agora Lean e Kanban. Mais do que isso, muitas empresas estão realmente adotando e implementando essas metodologias, muitos estão treinando como implementá-las, muitos ainda tentando entender a diferença entre uma e outra. Porém, existem questões fundamentais que permeiam todas essas metodologias e que, surpreendentemente, parece que poucos estão dando real atenção e, justamente por isso, a maioria das implementações dita ’ágeis’ nas empresas está destinada a fracassar. Nesta palestra vamos tentar entender qual é o ponto fundamental que será a diferença entre sucesso e fracasso na implementações ágeis";
	$palestras['a-semente-nao-entendida-de-todas-as-metodologias']['palestrante'] = "Fabio Akita";
	$palestras['a-semente-nao-entendida-de-todas-as-metodologias']['biografia']   = "Fabio Akita é co-fundador da Codeminer 42. Junto com a Locaweb organiza a RubyConf Brazil desde 2008 e é evangelista de Ruby e boas práticas de projetos de software em geral desde 2006. Trabalhou em diversos mercados, desde pequenas agências e produtoras multimídia nos anos 90, startups da primeira geração em 2000, mercado corporativo SAP a partir de 2002 e software livre em geral a partir de 2006. Palestrou em diversos eventos de tecnologia no Brazil e no exterior incluindo RailsConf US e RubyKaigi no Japão";

	$palestras['inovacao-centrada-no-usuario']['titulo']      = "Inovação centrada no usuário: criando os produtos que a sua vovó vai usar e você vai ficar feliz em comprar";
	$palestras['inovacao-centrada-no-usuario']['descricao']   = "Com a necessidade de inovar se tornando cada vez mais urgente nas agendas das organizações, investir apenas na inovação de base tecnológica mostrou-se uma estratégia com limitações claras. Neste cenário, um paradigma de inovação cada vez mais popular é a chamada Inovação Centrada no Usuário. Nesta perspectiva, o processo de inovação se dá a partir da inspiração nos hábitos e contextos do consumidor. A Inovação Centrada no Usuário parte da premissa de que inovações devem ser geradas de forma a – baseadas no entendimento do usuário – solucionar problemas e atender demandas identificadas em um contexto social específico.";
	$palestras['inovacao-centrada-no-usuario']['palestrante'] = "Dr. Paulo Melo";
	$palestras['inovacao-centrada-no-usuario']['biografia']   = "Paulo Melo é psicólogo e mestre em Psicologia Cognitiva pela UFPE. Em 2010, ele concluiu o doutorado profissional em User-system Interaction na University of Technology Eindhoven (Holanda). Profissionalmente, Paulo atuou como Designer de Interação e Especialista em Usabilidade no CESAR e CSIRO (Austrália). Nos últimos anos, ele tem atuado na área de Experiência do Usuário (UX), onde trabalhou pelo CESAR Sul, Philips e In/situm. Ao longo de sua experiência profissional, Paulo participou de projetos ligados a jogos para aparelhos celulares, acessibilidade, aplicações médicas, TV digital, sistemas de informação e design de produtos. Atualmente Paulo é gerente de negócios para projetos em UX no CESAR em São Paulo.";

	$palestras['sexo-drogas-e-software']['titulo']      = "Sexo, Drogas e Software: Filosofando nas Trincheiras entre o Bem e o Mal";
	$palestras['sexo-drogas-e-software']['descricao']   = "Usuários de software privativo são vítimas de estupro, de pedofilia ou apenas gostam de sacanagem?  Ficam impotentes quando tentam abandonar o vício?  Será que os traficantes de software privativo, pedófilos e estupradores de usuários, vão algum dia achar que exageraram no gozo do poder?  Temas pesados discutidos explicitamente, com pitadas de humor levemente apimentado.  Não recomendado para menores de XXX anos.";
	$palestras['sexo-drogas-e-software']['palestrante'] = "Alexandre Oliva";
	$palestras['sexo-drogas-e-software']['biografia']   = "Alexandre Oliva é ativista pela liberdade de software e pelo software livre; conselheiro da FSFLA, Fundação Software Livre América Latina; mantenedor do GNU Linux-libre, uma versão do núcleo Linux sem as armadilhas privativas de liberdade presentes na versão original; co-mantenedor da GNU libc e de porções do GCC e GNU binutils; co-autor do livro A Revolução do Software Livre, publicado pela Comunidade Sol; colunista da Revista Espírito Livre; engenheiro de compiladores livres na Red Hat Brasil; engenheiro de computação e mestre em ciências da computação formado na Unicamp.";

	$palestras['comecando-com-nodejs']['titulo']      = "Começando com Node.JS";
	$palestras['comecando-com-nodejs']['descricao']   = "Veja como desenvolver aplicativos realtime usando Node.js nesta introdução prática. Você verá alguns conceitos de JavaScript, além de um tutorial prático de Node.js. Conheça mais sobre o palestrante e os seus projetos em http://nandovieira.com.br/";
	$palestras['comecando-com-nodejs']['palestrante'] = "Nando Vieira - CodePlane, HowToCode, Hellobits";
	$palestras['comecando-com-nodejs']['biografia']   = "Conheça mais sobre o Nando e os seus projetos em http://nandovieira.com.br/";

	$palestras['projeto-domus']['titulo']      = "Projeto DOMUS: Eficiência Energética em Edificações";
	$palestras['projeto-domus']['descricao']   = "O tema central da palestra é o projeto Domus, software para simulação termoenergética de edificações desenvolvido em ambiente acadêmico com o apoio do CNPq e da Eletrobras, e que tem como objetivo proporcionar a otimização do projeto de edificações em termos da eficiência energética. O software possibilita o estudo das trocas higrotérmicas (temperatura e umidade) através das alvenarias do edifício, fato que os outros programas não consideram e é de fundamental importância no clima brasileiro.  O Domus simula ainda a classificação do edifício quanto ao nível de eficiência energética visando à etiquetagem, segundo o Programa Brasileiro de Etiquetagem de Edifícios. Nesta palestra, serão apresentadas características técnicas do desenvolvimento do software e ao final será feita uma demonstração por meio de uma simulação.";
	$palestras['projeto-domus']['palestrante'] = "Dr. Ricardo C. L. F. Oliveira";
	$palestras['projeto-domus']['biografia']   = "Ricardo Oliveira é professor da Faculdade de Engenharia Elétrica e de Computação (FEEC) da UNICAMP desde 2010. Formou-se em engenharia da computação na PUC-PR (2000), fez mestrado (2003), doutorado (2006) e pós-doutorado (2009) na FEEC-UNICAMP. Suas pesquisas são voltadas para o desenvolvimento de ferramentas numéricas para análise, controle e simulação de sistemas dinâmicos. Atualmente, é vice-coordenador do Departamento de Telemática e bolsista de produtividade em pesquisa do CNPq.";

	$palestras['recuperacao-de-informacao-visual']['titulo']      = "Recuperação de Informação Visual";
	$palestras['recuperacao-de-informacao-visual']['descricao']   = "Avanços em técnicas de aquisição, compressão e transmissão de dados têm permitido a criação de bibliotecas de mídia digital cada vez maiores. Na medida em que cresce o volume de imagens e vídeos nessas coleções, cresce também o interesse em sistemas capazes de gerenciá-los de maneira eficiente. Essa dificuldade vem sendo resolvida por meio de sistemas capazes de abstrair representações semânticas de alto nível a partir das informações de baixo nível desses dados. Devido à complexidade desse material, existem quatro desafios principais na construção tais sistemas: (1) implementar algoritmos para codificar as propriedades de baixo nível de imagens e vídeos em vetores de características; (2) desenvolver uma medida de similaridade para comparar esses dados a partir de seus vetores; (3) responder rapidamente a consultas por similaridade sobre, potencialmente, milhões de entradas; e (4) apresentar os resultados de forma amigável ao usuário. Inúmeras técnicas têm sido propostas para atender a esses requisitos. Todavia, apesar de todos os esforços o gerenciamento de dados mutimídia ainda está em seu estado preliminar. Este seminário apresenta uma visão geral de diferentes métodos propostos para atender aos quesitos supracitados, analisando as suas contribuições teóricas e empíricas para a recuperação de informação visual.";
	$palestras['recuperacao-de-informacao-visual']['palestrante'] = "Dr. Jurandy G. Almeida Jr";
	$palestras['recuperacao-de-informacao-visual']['biografia']   = "Jurandy Almeida possui graduação em Ciência da Computação (UNESP, 2004), mestrado (2007) e doutorado (2011) em Ciência da Computação (UNICAMP), com estágio doutoral no Dept. of Computing Science, University of Alberta em Edmonton, Canadá. Atualmente, é pesquisador colaborador e realiza estágio pós-doutoral no Instituto de Computação da UNICAMP. Possui trabalhos publicados em renomadas revistas e conferências nacionais e internacionais. Realiza pesquisa nas áreas de Banco de Dados, Processamento de Imagens e Visão Computacional, atuando, principalmente, em temas relacionados à Recuperação de Imagens e Vídeos.";

	$palestras['coding-dojo']['titulo']      = "Coding Dojo";
	$palestras['coding-dojo']['descricao']   = "Um Coding Dojo é um encontro onde um grupo de programadores de vários níveis de conhecimento se reúne para treinar, em um ambiente inclusivo e colaborativo boas técnicas e metodologias de desenvolvimento de software através da solução de um pequeno desafio de programação.";
	$palestras['coding-dojo']['palestrante'] = "Eher - Apontador";
	$palestras['coding-dojo']['biografia']   = "";

?>